### PR TITLE
Allow network 3.0.1.0

### PR DESCRIPTION
**Pull request by tfausak**
https://github.com/commercialhaskell/stackage/issues/4427

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
I just checked, and it actually builds with 3.1.0.0 as well.

**Comment by 23Skidoo** [comment]
Bumped the bounds for `ekg` and `ekg-statsd` on Hackage.

**Comment by tfausak** [comment]
Thanks!

**Pull request merged**
