### PR TITLE
Report counters in an incremental fashion.

### PR DESCRIPTION
**Pull request by j6carey**
Commit e444d8b680e92c4e8a45319ee41956433025b28d
eliminated the suppression of messages that were
in some sense redundant, but as a side effect
it started reporting the current counter value
instead of the increment since the last report.

This change causes only the increment to be
reported--which is what statsd servers expect.

Gauges are unaffected.  This change affects
only counters, but that includes the counter
within each distribution.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@adinapoli-iohk Ping.

**Comment by j6carey** [comment]
@23Skidoo , @adinapoli-iohk , I merged master.

**Comment by 23Skidoo** [comment]
@j6carey Can you please add a notice to the changelog?

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Released on Hackage as `ekg-statsd-0.2.5.0`.

**Comment by j6carey** [comment]
@23Skidoo , thanks!

**Pull request merged**
